name: Deploy App ARM (EU) to Amazon EKS - Staging

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.MY_AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.MY_ECR_REPOSITORY_APP }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04-arm
    environment: ch-staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          FINAL_TAG: ${{ vars.MY_FINAL_TAG_ARM }}
        run: |
          docker build --platform linux/arm64 -f Dockerfile.stg.arm --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$FINAL_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$FINAL_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update EKS Deployment with new image
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          KUBE_DEPLOYMENT: ${{ vars.MY_EKS_DEPLOYMENT_NAME }}
          KUBE_NAMESPACE: ${{ vars.MY_EKS_NAMESPACE }}
          KUBE_CONTAINER: ${{ vars.MY_EKS_CONTAINER_NAME }}
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          aws eks update-kubeconfig --region $AWS_REGION --name ${{ vars.MY_EKS_CLUSTER }}
          kubectl set image deployment/$KUBE_DEPLOYMENT $KUBE_CONTAINER=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -n $KUBE_NAMESPACE
          kubectl rollout restart deployment/$KUBE_DEPLOYMENT -n $KUBE_NAMESPACE
          kubectl rollout status deployment/$KUBE_DEPLOYMENT -n $KUBE_NAMESPACE
